--- name:vortex

position_commands: 0

m_max_speed: 0.01

gain: 1

num_joints: 5

model_initial_config: [1.570796,0,-2.21,0,0]
real_initial_config: [0,0,0,0,0]

joints_direction: [-1,-1,1,-1,1]

smooth_factor: 0.9 # 0 for non smoothing, 0.9 for big smoothing

negative_angles: 0   

sweep_movement_file: '../../../exoter/data/arm_movements/sweep_movement.txt'

--- name:exoter

position_commands: 1

m_max_speed: 0.01

gain: 1

num_joints: 5

model_initial_config: [1.570796,0,-2.21,0,0]
real_initial_config: [0,-1.570796,2.21,-1.570796,0]

joints_direction: [-1,-1,-1,1,1]

smooth_factor: 0.9 # 0 for non smoothing, 0.9 for big smoothing

negative_angles: 1 

sweep_movement_file: '../../../exoter/data/arm_movements/sweep_movement.txt'
