--- name:exoter_kinova

# Number of Kinova arm joints
num_arm_joints: 8  

# Number of gripper parts

num_gripper: 2

#last_movement_waypoints:  6
last_movement_waypoints: 5 

# Vector with the joints final position (defined with MatLab)
joints_final_position: [3.1416, -1.9635, -1.9635, 0, 1.5708, 3.1416, 0, 0]

# Opened gripper position
open_gripper_position: [-0.8, -0.8]

# Closed gripper position
#final_gripper_position: [0.2, 0.2]
final_gripper_position: [0.3, 0.3]

#RoCK kinematic model, equal to the joints_final_position but with opposite numbers
arm_model_initial_config: [-3.1416, 1.9635, 1.9635, 0, -1.5708, -3.1416, 0, 0]

#Vortex model
arm_real_initial_config: [0,0,0,0,0,0,0,0]

arm_joints_direction: [1,1,1,1,1,1,1,1]

negative_angles: 1 

arm_ground_distance: 0.15

#body_ground_distance: 0.279
body_ground_distance: 0.29
#body_ground_distance: 0.287

#arm_base_position: [-0.02297382, 0.17119076-0.05, 0.24582566-0.05]
arm_base_position: [-0.02297382, 0.1212, 0.1958]

rover_body_position: [-0.22999576, 0.27017041, 0.27899063]

arm_base_orientation: [0, 1.570796327, 0]

rover_body_orientation: [0, 0, 0]

#linksLength: [ (128.3 / 2) * pow(10, -3), (115 / 2) * pow(10, -3), (280 / 2) * pow(10, -3), (140 / 2) * pow(10, -3), (105 / 2) * pow(10, -3), (105 / 2) * pow(10, -3), (130 / 2) * pow(10, -3)]
linksLength: [0.0642, 0.0575, 0.14, 0.07, 0.0525, 0.0525, 0.065]


#X distance between the centre of the rover and the arm base, given by the transformation matrix TRB (Transformation rover -> base)
#double x_distance_roverCentre_armBase = 0.207;
x_distance_roverCentre_armBase: 0.207

# Y distance between the centre of the rover and the arm base, given by the transformation matrix TRB (Transformation rover -> base)
#double y_distance_roverCentre_armBase = -0.099-0.05;
y_distance_roverCentre_armBase:  -0.149

