--- name:default
# maximum latency, in seconds, of the stream aligner. The aligner will start dropping samples if the difference between the last output and last input is greater than this
aggregator_max_latency: 0.5
# minimum time, in s, between two sequential samples arrive on inertial_delta_pose_in
inertial_delta_pose_in_period: 0.0
# minimum system time in s between two status readings
stream_aligner_status_period: 1.0
# minimum time, in s, between two sequential samples arrive on visual_delta_pose_in
visual_delta_pose_in_period: 0.0
